services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: esportpro-app
    ports:
      - "3333:3333"
      - "24678:24678" # Vite HMR
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - db
    networks:
      - esportpro-network

  db:
    image: postgres:16-alpine
    container_name: esportpro-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_DATABASE:-esportpro}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - esportpro-network

volumes:
  postgres_data:

networks:
  esportpro-network:
