services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: esportpro-app
    ports:
      - "3333:3333"
      - "24678:24678" # Vite HMR
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - db
      - redis
    networks:
      - esportpro-network
    command: sh -c "npm install && npm run dev"

  db:
    image: postgres:16-alpine
    container_name: esportpro-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_DATABASE:-esportpro}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - esportpro-network

  redis:
    image: redis:7-alpine
    container_name: esportpro-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - esportpro-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:

networks:
  esportpro-network:
